name: Build and Release

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [windows-latest, ubuntu-latest]

        permissions:
            contents: write
            packages: write
            issues: write
            pull-requests: read

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "22"

            - name: Install dependencies
              run: npm install

            - name: Generate Release Notes
              id: generate_release_notes
              uses: mikepenz/release-changelog-builder-action@v5
              with:
                  configuration: .github/changelog-config.json
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Make distributables
              run: npm run make

            - name: Publish to GitHub Releases
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  RELEASE_NOTES: ${{ steps.generate_release_notes.outputs.changelog }}
              run: |
                  # Add release notes to electron-forge publish
                  echo 'RELEASE_NOTES<<EOF' >> $GITHUB_ENV
                  echo "${{ steps.generate_release_notes.outputs.changelog }}" >> $GITHUB_ENV
                  echo 'EOF' >> $GITHUB_ENV
                  npm run publish
